### ISSUE TITLE
Failed to fetch browser webSocket URL from http://127.0.0.1:34673/json/version

### ISSUE THREAD

**Issue by Hartyshow26** [ZFC-Digital/puppeteer-real-browser#217]
### Description

Hi,

When I have a simple page test.js :

`import { connect } from 'puppeteer-real-browser'

const { page, browser } = await connect({
  turnstile: true,
});`

with real-browser version 1.3.17 and when I launch my test.js, I have the following error :

`file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:67
        const result = await globalThis.fetch(endpointURL.toString(), {
                                        ^

TypeError: Failed to fetch browser webSocket URL from http://127.0.0.1:34673/json/version: globalThis.fetch is not a function
    at getWSEndpoint (file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:67:41)
    at getConnectionTransport (file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:54:37)
    at _connectToBrowser (file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:24:56)
    at PuppeteerNode.connect (file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/Puppeteer.js:95:16)
    at PuppeteerNode.connect (file:///XXXX/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:88:22)
    at connect (file:///XXXX/node_modules/puppeteer-real-browser/lib/esm/index.mjs:54:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///XXXX/test.js:2:27`

### Full steps to reproduce the issue

`import { connect } from 'puppeteer-real-browser'

const { page, browser } = await connect({
  turnstile: true,
});`

with real-browser 1.3.17 and just the command node test.js

### Issue Type

Bug

### Operating System

Linux

### Do you use Docker?

None

**Comment by RubberArchind** [comment]
Where you run this? what OS

**Comment by Hartyshow26** [comment]
Ubuntu 22.04.5 LTS
Node 16.18.1

**Comment by RubberArchind** [comment]
Ok after try it i can confirm that nodejs was the problem for you, try to upgrade it, at least to version 20.

**Comment by Hartyshow26** [comment]
Oh ok ok, in fact I've tried with a higher version of nodejs and it works ! Thank you for your help !
