### ISSUE TITLE
close page error

### ISSUE THREAD

**Issue by baba990aini** [ZFC-Digital/puppeteer-real-browser#229]
### Description

import { connect } from 'puppeteer-real-browser'

const { browser, page } = await connect({
  headless: false,
  args: [],
  customConfig: {},
  turnstile: true,
  connectOption: {},
  disableXvfb: false,
  ignoreAllFlags: false
})

let testPage = await browser.newPage()

testPage.on('response', async (response) => {
  if (response.url().includes(`?type=dealer&type=spclient`)) {
    testPage.close()
  }
})

await testPage.goto(`https://open.spotify.com/search/lady gaga`)

### Full steps to reproduce the issue

file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:100
            this.#terminationDeferred.resolve(new Error('Navigating frame was detached'));
                                              ^

Error: Navigating frame was detached
    at #onFrameDetached (file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:100:47)
    at file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
    at Array.map (<anonymous>)
    at Object.emit (file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/third_party/mitt/mitt.js:35:20)
    at CdpFrame.emit (file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:77:23)
    at #removeFramesRecursively (file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:514:15)
    at #onClientDisconnect (file:///Users/fengyu/Desktop/AI/express/node_modules/rebrowser-puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:91:42)

Node.js v20.17.0
[nodemon] app crashed - waiting for file changes before starting...

### Do you use Docker?

None

**Comment by RubberArchind** [comment]
it seems like its run testPage.close() multiple times even after the page is already closed

**Comment by baba990aini** [comment]
> it seems like its run testPage.close() multiple times even after the page is already closed

Solved, thank you
