### ISSUE TITLE
Headless: true is not working, or just me?

### ISSUE THREAD

**Issue by dante4rt** [ZFC-Digital/puppeteer-real-browser#233]
### Description

The error:

```
Waiting for the API response...
Error: TimeoutError: Timed out after waiting 30000ms
    at /Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/puppeteer/common/util.js:256:19
    at /Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3986:35
    at OperatorSubscriber2._this._next (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1055:13)
    at Subscriber2.next (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:678:16)
    at AsyncAction2.<anonymous> (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:4863:24)
    at AsyncAction2._execute (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1974:16)
    at AsyncAction2.execute (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1963:26)
    at AsyncScheduler2.flush (/Users/dantezy/Downloads/HEHE/AFTER-GRAD/TRY/Random/insider-trading-bot/node_modules/rebrowser-puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:2235:30)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  [cause]: undefined
}
```

### Full steps to reproduce the issue

1. Hit an API
2. Wait
3. The error will shown

### Issue Type

Bug

### Operating System

Mac OS

### Do you use Docker?

None

**Comment by mdervisaygan** [comment]
Headless true leaves countless leaks and is detected. For this reason it is not supported.
